"use client";


import AdminLayout from '@/components/admin/Layout'
import { LineTitle } from '@/components/admin/LineTitle'
import React, { useCallback, useState } from 'react'
import Link from 'next/link'



// const metadata: Metadata = {
//     title: "Settings Page",
//     description: "Generated by create next app",
//   };




const Ulist = (prop:{url?:string, title?:string, has_dropdown:boolean, dropdown_content?:{title:string, url:string}[], onclick?:React.MouseEventHandler<HTMLAnchorElement>}) => {
    return (
        <ul className='flex flex-col space-y-5 font-sans'>
            {prop.has_dropdown? (
                <li className='hover:bg-red-100 p-1'>
                    <Link href={`#`} >{`${prop.title}`}</Link>
                    <ul className='ml-3'>
                        <li className='hover:bg-red-100 p-1'>
                            <Link href={`${prop.url}`} onClick={prop.onclick} >{`${prop.title}`}</Link>
                        </li>
                    </ul>
                </li>
            ) : (
                <li className='hover:bg-red-100 p-1' >
                    <Link href={`${prop.url}`} onClick={prop.onclick} >{`${prop.title}`}</Link>
                </li>
            )}
        </ul>
    )
}


const Home = () => {
    const [page, setPage] = useState("/admin/settings/general_settings");

    const loadpage = useCallback((event:React.MouseEvent<HTMLAnchorElement>) => {
            event.preventDefault();
            setPage(event.currentTarget?.href);
    }, [])


  return (
    <AdminLayout >
        <main className='flex flex-col space-y-4'>
            <div>
                <LineTitle heading={'Application Settings'}  />
            </div>

            <div className='flex flex-row mb-3'>
                <div className='shrink-0 w-1/5 bg-gray-100 h-screen p-2 space-y-4'>
                    <Ulist title='General Settings' onclick={loadpage} url='/admin/settings/general_settings' has_dropdown={false}></Ulist>

                    <Ulist title='Sms Settings' onclick={loadpage} url='/admin/settings/sms_settings' has_dropdown={false}></Ulist>
                </div>
                
                <div className=' w-4/5 h-screen'>
                    {page ? (
                        <iframe src={`${page}`} className='w-full h-screen font-sans m-0'></iframe>
                    ) : 'loading data...' }
                </div>
            </div>
        </main>

    </AdminLayout>
  )
}

export default Home
